---
title: "Applied Data Science:  Midterm Project"
author: "Group 28"
date: ""
output:
  prettydoc::html_pretty:
  theme: cayman
highlight: github
---

```{r setup, include=FALSE}
set.seed(72)
knitr::opts_chunk$set(echo = TRUE, comment="", warning = FALSE, message = FALSE, tidy.opts=list(width.cutoff=55))
```

```{r libraries, echo = FALSE}
library(data.table)
library(DT)
library(knitr) # for knitting document
library(data.table) # increase speed of dataframe reading
library(dplyr)
library(nnet)
library(class)
library(rpart)
library(randomForest)
library(glmnet)
```

```{r source_files}

```

```{r functions}
get_image <- function(x) {image(
         matrix(unlist(train[x,-1]),ncol = 7,byrow = T),
         col=cm.colors(255),    # Select 255 grey levels
         axes = FALSE
       )
}

```

```{r constants}
n.values <- c(500, 1000, 2000)
iterations <- 3
```

```{r load_data}
train <- fread("MNIST-fashion training set-49.csv")
test <- fread("MNIST-fashion testing set-49.csv")
lapply(1:9, get_image)#visulization of first 9 images
```

```{r clean_data}
# normalize the values of each pixel
train[,2:50] <-  train[,2:50]/255
test[,2:50] <- test[,2:50]/255


train$label <- as.factor(train$label) #change characters to factors
test$label <- as.factor(test$label)
```

```{r generate_samples}
#Create 9 different size data sets
for (i in 1:iterations)
{
  for (j in n.values)
  {
    nam <- paste("dat", j,i, sep = "_")
    assign(nam, sample_n(train, j))

  }
}
```

## Introduction


### Model 1 Multinomial logistic regression:  


```{r code_model1_development, eval = TRUE}
Multinomial_logistic_regression <- function(data)
{
  regression <- multinom(data$label~.,data = data, trace=FALSE)
  
  start_time <- as.numeric(Sys.time())
  pred <- predict(object = regression, newdata = test)
  end_time <- as.numeric(Sys.time())
  
  size = nrow(data)
  
  A = size/nrow(train)
  
  B = min(1,(end_time - start_time-60)/60)

  C = 1-sum(test$label==pred)/nrow(test)
  
  return(data.table(Model='Model 1','Sample size'=size,Data=deparse(substitute(data)),A=A,B=B,C=C,score=0.25 * A + 0.25 * B + 0.5 * C))
}
```

```{r load_model1}
Multinomial_logistic_regression(dat_500_1)
Multinomial_logistic_regression(dat_1000_1)
Multinomial_logistic_regression(dat_2000_1)
```

### Model 2 K(5)-Nearest Neighbors :  


```{r code_model2_development, eval = TRUE}
K_Nearest_Neighbors <- function(data,k=5)
{
  
  
  start_time <- as.numeric(Sys.time())
  pred <- knn(data[,2:50],test = test[,2:50],,cl=data$label,k=k)
  end_time <- as.numeric(Sys.time())
  
  size = nrow(data)
  
  A = size/nrow(train)
  
  B = min(1,(end_time - start_time-60)/60)

  C = 1-sum(test$label==pred)/nrow(test)
  
  return(data.table(Model='Model 2','Sample size'=size,Data=deparse(substitute(data)),A=A,B=B,C=C,score=0.25 * A + 0.25 * B + 0.5 * C))
}

```

```{r load_model2}
K_Nearest_Neighbors(dat_1000_1)
```

### Model 3 Classification Tree:  


```{r code_model3_development, eval = TRUE}

testlabel <- rpart(test$label~.,data = test,method = "class")


Classification_Tree <- function(data)
{

  start_time <- as.numeric(Sys.time())
  reg <- rpart(data$label~.,data = data,method = "class")
  pred=predict(object = reg, newdata = test,type = "vector")
  
  end_time <- as.numeric(Sys.time())
  
  
  
  size = nrow(data)
  
  A = size/nrow(train)
  
  B = min(1,(end_time - start_time-60)/60)

  C = 1-sum(testlabel$y==pred)/nrow(test)
  
  return(data.table(Model='Model 3','Sample size'=size,Data=deparse(substitute(data)),A=A,B=B,C=C,score=0.25 * A + 0.25 * B + 0.5 * C))
}
```

```{r load_model3}
Classification_Tree(dat_1000_1)
```

### Model 4 Random Forest:


```{r code_model4_development, eval = TRUE}
Random_Forest <- function(data)
{

  start_time <- as.numeric(Sys.time())
  mod.rf <- randomForest(formula =data$label~.,data=data)
  pred.rf <- predict(object = mod.rf, newdata = test)
  
  end_time <- as.numeric(Sys.time())
  
  
  
  size = nrow(data)
  
  A = size/nrow(train)
  
  B = min(1,(end_time - start_time-60)/60)

  C = 1-sum(test$label==pred.rf)/nrow(test)
  
  return(data.table(Model='Model 4','Sample size'=size,Data=deparse(substitute(data)),A=A,B=B,C=C,score=0.25 * A + 0.25 * B + 0.5 * C))
}
```

```{r load_model4}
Random_Forest(dat_1000_1)
```

### Model 5 Ridge Regression:


```{r code_model5_development, eval = TRUE}

```

```{r load_model5}

```

### Model 6


```{r code_model6_development, eval = TRUE}

```

```{r load_model6}

```

### Model 7


```{r code_model7_development, eval = TRUE}

```

```{r load_model7}

```

### Model 8


```{r code_model8_development, eval = TRUE}

```

```{r load_model8}

```

### Model 9


```{r code_model9_development, eval = TRUE}

```

```{r load_model9}

```

### Model 10


```{r code_model10_development, eval = TRUE}

```

```{r load_model10}

```

## Scoreboard

```{r scoreboard}

```

## Discussion


## References


